### ISSUE TITLE
Have TeardownHelper not centralized in the main module?

### ISSUE THREAD

**Issue by eyousefi** [dropbox/kaiken#29]
Currently for our usecase, TeardownHelper is init'd in the main app and currently has to dispatch any TeardownEvents directly from the teardown() func.
I.E. in the dropbox app (not in any module), this looks something like:

```
    @Provides
    @UserScope
    fun provideTeardownHelper(
        uploadManager: UploadManager
    ): TeardownHelper = DbappTeardownHelper(uploadManager = uploadManager)

class DbappTeardownHelper(private val uploadManager: UploadManager? = null) : TeardownHelper {
    override fun teardown() {
        uploadManager?.onTearDown()
    }
}
```

While i have some gaps in my knowledge on how kaiken works under the hood, is it not possible to make TeardownHelper into a factory delegate so that each module can provide a teardown helper directly from the module it self rather than centralizing the Teardown dispatch in the main app?

I.E. for ex:

Kaiken provides a TeardownHelperDelegate which takes in TeardownHelpers by TeardownHelperDelegate.registerTeardownListener().
Then in the modules, we can simply pull in TeardownHelperDelegate in the modules and add on our teardown logic in the module? (this should take place in onCreate)

**Comment by rodgavila** [comment]
Interesting idea. Are you envisioning something like this...

```
interface TerdownHelper {
    fun teardown()
}

interface TeardownHelperDelegate {
    fun registerTeardownHelper(registerTeardownHelper: helper)
}
```

Now let's say you have a module `FooModule` that contains a `BarManager` that needs to be teardown:

````
@Module
class FooModule {

    @UserScope
    fun barManager(teardownHelperDelegate: delegate): BarManager {
          val barManager = new BarManager(...)

          teardownHelperDelegate.registerTearDownListener(teardownHelper: {
               barManager.teardown()
          }
          )
    }
}

```

My only concern would be that our graph creation would have side-effects, but that might be better than having a centralized teardown. @chris-mitchell what do you think?

**Comment by eyousefi** [comment]
Exactly that. Alternatively I was first trying to see if i can just contribute another instance of TeardownHelper to the graph via @Provides (and avoid all the registering etc), but that runs into conflicts and I am not sure if we can add the ability to recognize multiple provides for an object in the dependency graph, so a delegate/factory would be great in this case. It's also quite useful for non-ui based service modules.

**Comment by rodgavila** [comment]
I totally agree on the pro of encapsulating the teardown logic in the module. Can you comment a little bit more on "It's also quite useful for non-ui based service modules."? Reason I'm asking is that I believe that currently all services that are being teardowned are non-ui based (e.g. device storage, upload & download queues).

**Comment by eyousefi** [comment]
> I totally agree on the pro of encapsulating the teardown logic in the module. Can you comment a little bit more on "It's also quite useful for non-ui based service modules."? Reason I'm asking is that I believe that currently all services that are being teardowned are non-ui based (e.g. device storage, upload & download queues).

I think i miscommunicated in my response, I meant to say this addition would be great for kaiken scoped service modules like the ones you mentioned, e.g. the current work I'm doing is rewriting uploads into a kaiken userscoped module and it would be good encapsulate this logic in the module it self.
